/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Outlet: typeof import('react-router-dom').Outlet
  const RouterProvider: typeof import('react-router-dom').RouterProvider
  const StrictMode: typeof import('react').StrictMode
  const Suspense: typeof import('react').Suspense
  const ThemeProvider: typeof import('styled-components').ThemeProvider
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cloneElement: typeof import('react').cloneElement
  const createBrowserRouter: typeof import('react-router-dom').createBrowserRouter
  const createContext: typeof import('react').createContext
  const createGlobalStyle: typeof import('styled-components').createGlobalStyle
  const createRef: typeof import('react').createRef
  const css: typeof import('styled-components').css
  const forwardRef: typeof import('react').forwardRef
  const keyframes: typeof import('styled-components').keyframes
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const styled: typeof import('styled-components').default
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useBeforeUnload: typeof import('react-router-dom').useBeforeUnload
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMatch: typeof import('react-router-dom').useMatch
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useOptimistic: typeof import('react').useOptimistic
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FunctionComponent, ReactNode, ReactElement, Key, MouseEvent as ReactMouseEvent, KeyboardEvent as ReactKeyboardEvent, ComponentType, ComponentProps, ChangeEvent, Ref, RefObject, Dispatch, SetStateAction } from 'react'
  import('react')
}
